CREATE TABLE "audit_events" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_events_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"invoice_id" text,
	"actor_type" text NOT NULL,
	"actor_user_id" text,
	"event" text NOT NULL,
	"from_state" text,
	"to_state" text,
	"detail_json" text NOT NULL,
	"created_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "audit_events_actor" CHECK ("audit_events"."actor_type" IN ('system', 'ai', 'user')),
	CONSTRAINT "audit_events_user" CHECK (("audit_events"."actor_type" = 'user') = ("audit_events"."actor_user_id" IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "creation_actions" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "creation_actions_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"invoice_id" text NOT NULL,
	"entity" text NOT NULL,
	"payload_json" text NOT NULL,
	"signature" text NOT NULL,
	"policy_code" text NOT NULL,
	"trigger" text NOT NULL,
	"approved_by_user_id" text,
	"question_id" text,
	"status" text NOT NULL,
	"erp_id" text,
	"idempotency_key" text NOT NULL,
	"created_at" timestamp(3) with time zone NOT NULL,
	"committed_at" timestamp(3) with time zone,
	CONSTRAINT "creation_actions_idempotency_key_unique" UNIQUE("idempotency_key"),
	CONSTRAINT "creation_actions_entity" CHECK ("creation_actions"."entity" IN ('vendor', 'item', 'alias', 'po', 'grn', 'vendor_reactivation')),
	CONSTRAINT "creation_actions_trigger" CHECK ("creation_actions"."trigger" IN ('auto_policy', 'user_approval')),
	CONSTRAINT "creation_actions_status" CHECK ("creation_actions"."status" IN ('staged', 'committed', 'discarded')),
	CONSTRAINT "creation_actions_committed" CHECK (("creation_actions"."status" = 'committed') = ("creation_actions"."erp_id" IS NOT NULL AND "creation_actions"."committed_at" IS NOT NULL)),
	CONSTRAINT "creation_actions_approval" CHECK ("creation_actions"."trigger" <> 'user_approval' OR ("creation_actions"."approved_by_user_id" IS NOT NULL AND "creation_actions"."question_id" IS NOT NULL)),
	CONSTRAINT "creation_actions_no_auto_grn_or_item" CHECK ("creation_actions"."entity" NOT IN ('grn', 'item', 'vendor_reactivation') OR "creation_actions"."trigger" = 'user_approval')
);
--> statement-breakpoint
CREATE TABLE "documents" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "documents_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"sha256" text NOT NULL,
	"filename" text NOT NULL,
	"mime" text NOT NULL,
	"size_bytes" integer NOT NULL,
	"storage_path" text NOT NULL,
	"uploaded_by_user_id" text NOT NULL,
	"uploaded_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "documents_sha256_unique" UNIQUE("sha256"),
	CONSTRAINT "documents_mime" CHECK ("documents"."mime" IN ('application/pdf', 'image/jpeg', 'image/png')),
	CONSTRAINT "documents_size" CHECK ("documents"."size_bytes" > 0)
);
--> statement-breakpoint
CREATE TABLE "erp_writes" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "erp_writes_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"idempotency_key" text PRIMARY KEY NOT NULL,
	"invoice_id" text NOT NULL,
	"operation" text NOT NULL,
	"status" text NOT NULL,
	"erp_id" text,
	"external_ref" text,
	"error_code" text,
	"created_at" timestamp(3) with time zone NOT NULL,
	"updated_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "erp_writes_status" CHECK ("erp_writes"."status" IN ('pending', 'confirmed', 'not_created', 'unknown', 'failed')),
	CONSTRAINT "erp_writes_confirmed" CHECK ("erp_writes"."status" <> 'confirmed' OR "erp_writes"."erp_id" IS NOT NULL)
);
--> statement-breakpoint
CREATE TABLE "extracted_fields" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "extracted_fields_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"invoice_id" text NOT NULL,
	"path" text NOT NULL,
	"value_json" text NOT NULL,
	"confidence_bp" integer,
	"evidence_json" text,
	"evidence_detail_json" text,
	"source" text NOT NULL,
	"method" text,
	"extraction_id" text,
	"updated_by_user_id" text,
	"updated_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "extracted_fields_source" CHECK ("extracted_fields"."source" IN ('extracted', 'human_confirmed', 'human_corrected', 'derived_from_erp_choice', 'derived_from_document_evidence')),
	CONSTRAINT "extracted_fields_method" CHECK ("extracted_fields"."method" IS NULL OR "extracted_fields"."method" IN ('pdf_text', 'tesseract', 'ollama', 'fixture')),
	CONSTRAINT "extracted_fields_confidence" CHECK ("extracted_fields"."confidence_bp" IS NULL OR "extracted_fields"."confidence_bp" BETWEEN 0 AND 10000),
	CONSTRAINT "extracted_fields_human" CHECK ("extracted_fields"."source" NOT IN ('human_confirmed', 'human_corrected') OR "extracted_fields"."updated_by_user_id" IS NOT NULL)
);
--> statement-breakpoint
CREATE TABLE "extractions" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "extractions_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"invoice_id" text NOT NULL,
	"extractor_id" text NOT NULL,
	"extractor_version" text NOT NULL,
	"raw_json" text NOT NULL,
	"created_at" timestamp(3) with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "imports" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "imports_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"files_json" text NOT NULL,
	"kinds" text NOT NULL,
	"status" text NOT NULL,
	"check_json" text NOT NULL,
	"result_json" text,
	"uploaded_by_user_id" text NOT NULL,
	"confirmed_by_user_id" text,
	"created_at" timestamp(3) with time zone NOT NULL,
	"confirmed_at" timestamp(3) with time zone,
	CONSTRAINT "imports_status" CHECK ("imports"."status" IN ('ready', 'invalid', 'imported')),
	CONSTRAINT "imports_confirmed" CHECK (("imports"."status" = 'imported') = ("imports"."result_json" IS NOT NULL AND "imports"."confirmed_at" IS NOT NULL AND "imports"."confirmed_by_user_id" IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "invoice_lines" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "invoice_lines_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"invoice_id" text NOT NULL,
	"line_no" integer NOT NULL,
	"item_erp_id" text,
	"po_line_erp_id" text,
	"item_ref_staged_action_id" text
);
--> statement-breakpoint
CREATE TABLE "invoices" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "invoices_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"document_id" text NOT NULL,
	"state" text NOT NULL,
	"state_version" integer NOT NULL,
	"run_no" integer NOT NULL,
	"vendor_erp_id" text,
	"po_erp_id" text,
	"erp_purchase_invoice_id" text,
	"dup_vendor_gstin" text,
	"dup_invoice_no" text,
	"dup_fy" text,
	"commit_plan_json" text,
	"failed_stage" text,
	"failure_reason" text,
	"rejected_by_user_id" text,
	"rejected_reason" text,
	"created_at" timestamp(3) with time zone NOT NULL,
	"updated_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "invoices_document_id_unique" UNIQUE("document_id"),
	CONSTRAINT "invoices_state" CHECK ("invoices"."state" IN ('UPLOADED', 'EXTRACTING', 'MATCHING', 'RESOLVING', 'VALIDATING', 'NEEDS_INPUT', 'COMMITTING', 'VERIFIED_PENDING_PAYMENT', 'REJECTED', 'FAILED'))
);
--> statement-breakpoint
CREATE TABLE "jobs" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "jobs_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"invoice_id" text NOT NULL,
	"type" text NOT NULL,
	"status" text NOT NULL,
	"attempts" integer NOT NULL,
	"run_after" timestamp(3) with time zone NOT NULL,
	"locked_at" timestamp(3) with time zone,
	"last_error" text,
	"created_at" timestamp(3) with time zone NOT NULL,
	"updated_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "jobs_type" CHECK ("jobs"."type" IN ('pipeline', 'commit')),
	CONSTRAINT "jobs_status" CHECK ("jobs"."status" IN ('queued', 'running', 'succeeded', 'failed'))
);
--> statement-breakpoint
CREATE TABLE "match_results" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "match_results_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"invoice_id" text NOT NULL,
	"run_no" integer NOT NULL,
	"entity" text NOT NULL,
	"line_no" integer,
	"outcome" text NOT NULL,
	"method" text NOT NULL,
	"candidates_json" text NOT NULL,
	"chosen_erp_id" text,
	CONSTRAINT "match_results_entity" CHECK ("match_results"."entity" IN ('vendor', 'item', 'po', 'grn')),
	CONSTRAINT "match_results_outcome" CHECK ("match_results"."outcome" IN ('found', 'not_found', 'ambiguous'))
);
--> statement-breakpoint
CREATE TABLE "questions" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "questions_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"invoice_id" text NOT NULL,
	"kind" text NOT NULL,
	"code" text NOT NULL,
	"subject_key" text NOT NULL,
	"prompt" text NOT NULL,
	"context_json" text NOT NULL,
	"options_json" text NOT NULL,
	"input_schema_json" text,
	"status" text NOT NULL,
	"assigned_to_user_id" text NOT NULL,
	"answer_json" text,
	"answered_by_user_id" text,
	"answered_at" timestamp(3) with time zone,
	"answer_seq" integer,
	"created_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "questions_kind" CHECK ("questions"."kind" IN ('MISSING_DATA', 'AMBIGUOUS_MATCH', 'BUSINESS_DECISION', 'VALIDATION_FAILURE', 'CREATION_APPROVAL')),
	CONSTRAINT "questions_status" CHECK ("questions"."status" IN ('open', 'answered', 'superseded')),
	CONSTRAINT "questions_answer" CHECK (("questions"."status" = 'answered') = ("questions"."answer_json" IS NOT NULL AND "questions"."answered_by_user_id" IS NOT NULL AND "questions"."answered_at" IS NOT NULL AND "questions"."answer_seq" IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "settings" (
	"key" text PRIMARY KEY NOT NULL,
	"value_json" text NOT NULL,
	"updated_by_user_id" text,
	"updated_at" timestamp(3) with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"active" boolean NOT NULL,
	"created_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "validation_results" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "validation_results_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"invoice_id" text NOT NULL,
	"run_no" integer NOT NULL,
	"rule_code" text NOT NULL,
	"line_no" integer,
	"outcome" text NOT NULL,
	"na_reason" text,
	"expected_json" text NOT NULL,
	"actual_json" text NOT NULL,
	"message" text NOT NULL,
	"created_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "validation_results_outcome" CHECK ("validation_results"."outcome" IN ('pass', 'fail', 'not_applicable', 'not_evaluated')),
	CONSTRAINT "validation_results_na" CHECK (("validation_results"."outcome" = 'not_applicable') = ("validation_results"."na_reason" IS NOT NULL))
);
--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "creation_actions" ADD CONSTRAINT "creation_actions_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "creation_actions" ADD CONSTRAINT "creation_actions_approved_by_user_id_users_id_fk" FOREIGN KEY ("approved_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "documents" ADD CONSTRAINT "documents_uploaded_by_user_id_users_id_fk" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "erp_writes" ADD CONSTRAINT "erp_writes_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "extracted_fields" ADD CONSTRAINT "extracted_fields_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "extracted_fields" ADD CONSTRAINT "extracted_fields_extraction_id_extractions_id_fk" FOREIGN KEY ("extraction_id") REFERENCES "public"."extractions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "extracted_fields" ADD CONSTRAINT "extracted_fields_updated_by_user_id_users_id_fk" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "extractions" ADD CONSTRAINT "extractions_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "imports" ADD CONSTRAINT "imports_uploaded_by_user_id_users_id_fk" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "imports" ADD CONSTRAINT "imports_confirmed_by_user_id_users_id_fk" FOREIGN KEY ("confirmed_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoice_lines" ADD CONSTRAINT "invoice_lines_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_document_id_documents_id_fk" FOREIGN KEY ("document_id") REFERENCES "public"."documents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_rejected_by_user_id_users_id_fk" FOREIGN KEY ("rejected_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "match_results" ADD CONSTRAINT "match_results_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "questions" ADD CONSTRAINT "questions_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "questions" ADD CONSTRAINT "questions_assigned_to_user_id_users_id_fk" FOREIGN KEY ("assigned_to_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "questions" ADD CONSTRAINT "questions_answered_by_user_id_users_id_fk" FOREIGN KEY ("answered_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "settings" ADD CONSTRAINT "settings_updated_by_user_id_users_id_fk" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "validation_results" ADD CONSTRAINT "validation_results_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_events_invoice" ON "audit_events" USING btree ("invoice_id");--> statement-breakpoint
CREATE INDEX "creation_actions_invoice" ON "creation_actions" USING btree ("invoice_id","status");--> statement-breakpoint
CREATE INDEX "erp_writes_invoice" ON "erp_writes" USING btree ("invoice_id");--> statement-breakpoint
CREATE UNIQUE INDEX "extracted_fields_path" ON "extracted_fields" USING btree ("invoice_id","path");--> statement-breakpoint
CREATE UNIQUE INDEX "invoice_lines_no" ON "invoice_lines" USING btree ("invoice_id","line_no");--> statement-breakpoint
CREATE INDEX "invoices_dup" ON "invoices" USING btree ("dup_vendor_gstin","dup_invoice_no","dup_fy");--> statement-breakpoint
CREATE INDEX "jobs_queue" ON "jobs" USING btree ("status","run_after");--> statement-breakpoint
CREATE INDEX "match_results_run" ON "match_results" USING btree ("invoice_id","run_no");--> statement-breakpoint
CREATE UNIQUE INDEX "questions_open_subject" ON "questions" USING btree ("invoice_id","code","subject_key") WHERE "questions"."status" = 'open';--> statement-breakpoint
CREATE INDEX "validation_results_run" ON "validation_results" USING btree ("invoice_id","run_no");