CREATE TABLE "organizations" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp(3) with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "sessions_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"token_hash" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"csrf_token" text NOT NULL,
	"created_at" timestamp(3) with time zone NOT NULL,
	"last_seen_at" timestamp(3) with time zone NOT NULL,
	"expires_at" timestamp(3) with time zone NOT NULL,
	"revoked_at" timestamp(3) with time zone
);
--> statement-breakpoint
-- Existing rows (Phase 6A databases) are kept: the new columns are added, filled, then required.
-- The organization row is renamed to the configured organization when the API starts.
INSERT INTO "organizations" ("id", "name", "created_at") VALUES ('00000000000000000000000001', 'Organization', now());--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "organization_id" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "role" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "password_hash" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "password_changed_at" timestamp(3) with time zone;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "updated_at" timestamp(3) with time zone;--> statement-breakpoint
-- The only pre-existing account is the designated approver (no password: it cannot sign in).
UPDATE "users" SET "organization_id" = '00000000000000000000000001', "role" = 'ADMIN', "updated_at" = "created_at", "email" = lower("email");--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "role" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "sessions_user" ON "sessions" USING btree ("user_id");--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_role" CHECK ("users"."role" IN ('ADMIN', 'FINANCE', 'REVIEWER'));--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_email_lower" CHECK ("users"."email" = lower("users"."email"));--> statement-breakpoint
CREATE TABLE "security_events" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "security_events_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"event" text NOT NULL,
	"user_id" text,
	"subject_user_id" text,
	"request_id" text,
	"detail_json" text NOT NULL,
	"created_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "security_events_event" CHECK ("security_events"."event" IN ('login.succeeded', 'login.failed', 'logout', 'user.created', 'user.updated', 'user.disabled', 'user.enabled', 'password.changed', 'password.reset', 'access.denied', 'document.accessed'))
);
--> statement-breakpoint
ALTER TABLE "security_events" ADD CONSTRAINT "security_events_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "security_events" ADD CONSTRAINT "security_events_subject_user_id_users_id_fk" FOREIGN KEY ("subject_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "security_events_created" ON "security_events" USING btree ("created_at");