-- Generated by drizzle-kit, then corrected by hand: the copy step selected the new `method`
-- column from the old table, where it does not exist yet. Existing rows get NULL (read method
-- unknown). See ARCHITECTURE §14.4.
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_extracted_fields` (
	`id` text PRIMARY KEY NOT NULL,
	`invoice_id` text NOT NULL,
	`path` text NOT NULL,
	`value_json` text NOT NULL,
	`confidence_bp` integer,
	`evidence_json` text,
	`evidence_detail_json` text,
	`source` text NOT NULL,
	`method` text,
	`extraction_id` text,
	`updated_by_user_id` text,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`invoice_id`) REFERENCES `invoices`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`extraction_id`) REFERENCES `extractions`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`updated_by_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "extracted_fields_source" CHECK("__new_extracted_fields"."source" IN ('extracted', 'human_confirmed', 'human_corrected', 'derived_from_erp_choice', 'derived_from_document_evidence')),
	CONSTRAINT "extracted_fields_method" CHECK("__new_extracted_fields"."method" IS NULL OR "__new_extracted_fields"."method" IN ('pdf_text', 'tesseract', 'ollama', 'fixture')),
	CONSTRAINT "extracted_fields_confidence" CHECK("__new_extracted_fields"."confidence_bp" IS NULL OR (typeof("__new_extracted_fields"."confidence_bp") = 'integer' AND "__new_extracted_fields"."confidence_bp" BETWEEN 0 AND 10000)),
	CONSTRAINT "extracted_fields_human" CHECK("__new_extracted_fields"."source" NOT IN ('human_confirmed', 'human_corrected') OR "__new_extracted_fields"."updated_by_user_id" IS NOT NULL)
);
--> statement-breakpoint
INSERT INTO `__new_extracted_fields`("id", "invoice_id", "path", "value_json", "confidence_bp", "evidence_json", "evidence_detail_json", "source", "method", "extraction_id", "updated_by_user_id", "updated_at") SELECT "id", "invoice_id", "path", "value_json", "confidence_bp", "evidence_json", "evidence_detail_json", "source", NULL, "extraction_id", "updated_by_user_id", "updated_at" FROM `extracted_fields`;--> statement-breakpoint
DROP TABLE `extracted_fields`;--> statement-breakpoint
ALTER TABLE `__new_extracted_fields` RENAME TO `extracted_fields`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE UNIQUE INDEX `extracted_fields_path` ON `extracted_fields` (`invoice_id`,`path`);