CREATE TABLE "commercial_events" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "commercial_events_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"event" text NOT NULL,
	"organization_id" text,
	"plan_key" text,
	"capability" text,
	"old_value_json" text,
	"new_value_json" text,
	"reason" text NOT NULL,
	"expires_at" timestamp(3) with time zone,
	"actor_user_id" text NOT NULL,
	"request_id" text,
	"created_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "commercial_events_event" CHECK ("commercial_events"."event" IN ('plan.assigned', 'plan.entitlement_changed', 'override.set', 'override.removed'))
);
--> statement-breakpoint
CREATE TABLE "entitlement_overrides" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "entitlement_overrides_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"organization_id" text NOT NULL,
	"capability" text NOT NULL,
	"enabled" boolean,
	"limit_value" bigint,
	"unlimited" boolean DEFAULT false NOT NULL,
	"reason" text NOT NULL,
	"expires_at" timestamp(3) with time zone,
	"created_by_user_id" text NOT NULL,
	"created_at" timestamp(3) with time zone NOT NULL,
	"revoked_at" timestamp(3) with time zone,
	"revoked_by_user_id" text,
	CONSTRAINT "entitlement_overrides_one_kind" CHECK (("entitlement_overrides"."enabled" IS NOT NULL) <> ("entitlement_overrides"."limit_value" IS NOT NULL OR "entitlement_overrides"."unlimited")),
	CONSTRAINT "entitlement_overrides_limit" CHECK ("entitlement_overrides"."limit_value" IS NULL OR "entitlement_overrides"."limit_value" >= 0),
	CONSTRAINT "entitlement_overrides_reason" CHECK (length(trim("entitlement_overrides"."reason")) > 0)
);
--> statement-breakpoint
CREATE TABLE "plan_entitlements" (
	"plan_key" text NOT NULL,
	"capability" text NOT NULL,
	"enabled" boolean,
	"limit_value" bigint,
	"updated_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "plan_entitlements_plan_key_capability_pk" PRIMARY KEY("plan_key","capability"),
	CONSTRAINT "plan_entitlements_one_kind" CHECK ("plan_entitlements"."enabled" IS NULL OR "plan_entitlements"."limit_value" IS NULL),
	CONSTRAINT "plan_entitlements_limit" CHECK ("plan_entitlements"."limit_value" IS NULL OR "plan_entitlements"."limit_value" >= 0)
);
--> statement-breakpoint
CREATE TABLE "plans" (
	"key" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"status" text NOT NULL,
	"description" text NOT NULL,
	"created_at" timestamp(3) with time zone NOT NULL,
	"updated_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "plans_status" CHECK ("plans"."status" IN ('active', 'retired'))
);
--> statement-breakpoint
ALTER TABLE "users" DROP CONSTRAINT "users_role";--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "plan_key" text;--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "plan_assigned_at" timestamp(3) with time zone;--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "commercial_status" text DEFAULT 'active' NOT NULL;--> statement-breakpoint
ALTER TABLE "commercial_events" ADD CONSTRAINT "commercial_events_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commercial_events" ADD CONSTRAINT "commercial_events_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entitlement_overrides" ADD CONSTRAINT "entitlement_overrides_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entitlement_overrides" ADD CONSTRAINT "entitlement_overrides_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entitlement_overrides" ADD CONSTRAINT "entitlement_overrides_revoked_by_user_id_users_id_fk" FOREIGN KEY ("revoked_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plan_entitlements" ADD CONSTRAINT "plan_entitlements_plan_key_plans_key_fk" FOREIGN KEY ("plan_key") REFERENCES "public"."plans"("key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "commercial_events_organization" ON "commercial_events" USING btree ("organization_id","seq");--> statement-breakpoint
CREATE UNIQUE INDEX "entitlement_overrides_active" ON "entitlement_overrides" USING btree ("organization_id","capability") WHERE "entitlement_overrides"."revoked_at" IS NULL;--> statement-breakpoint
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_plan_key_plans_key_fk" FOREIGN KEY ("plan_key") REFERENCES "public"."plans"("key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "documents_uploaded" ON "documents" USING btree ("uploaded_at");--> statement-breakpoint
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_commercial_status" CHECK ("organizations"."commercial_status" IN ('trial', 'active'));--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_platform_role" CHECK (("users"."role" = 'VEYRA_ADMIN') = ("users"."organization_id" = '00000000000000000000000000'));--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_role" CHECK ("users"."role" IN ('ADMIN', 'FINANCE', 'REVIEWER', 'VEYRA_ADMIN'));--> statement-breakpoint
-- Phase 8A seed: the initial plans (no prices: billing is separate), their entitlements, Veyra's
-- platform organization, and every existing customer organization on ENTERPRISE, so a deployment
-- that upgrades keeps exactly what it could do before.
INSERT INTO "plans" ("key", "name", "status", "description", "created_at", "updated_at") VALUES
  ('STARTER', 'Starter', 'active', 'Invoice processing for a small finance team.', now(), now()),
  ('BUSINESS', 'Business', 'active', 'Invoice processing with ERP imports and exports.', now(), now()),
  ('ENTERPRISE', 'Enterprise', 'active', 'Every capability, no quotas.', now(), now());--> statement-breakpoint
INSERT INTO "plan_entitlements" ("plan_key", "capability", "enabled", "limit_value", "updated_at") VALUES
  ('STARTER', 'erp.business_record_import', false, NULL, now()),
  ('STARTER', 'reports.exports', false, NULL, now()),
  ('STARTER', 'invoice.monthly_limit', NULL, 500, now()),
  ('STARTER', 'users.max', NULL, 3, now()),
  ('STARTER', 'storage.max_bytes', NULL, 5368709120, now()),
  ('BUSINESS', 'erp.business_record_import', true, NULL, now()),
  ('BUSINESS', 'reports.exports', true, NULL, now()),
  ('BUSINESS', 'invoice.monthly_limit', NULL, 2000, now()),
  ('BUSINESS', 'users.max', NULL, 10, now()),
  ('BUSINESS', 'storage.max_bytes', NULL, 21474836480, now()),
  ('ENTERPRISE', 'erp.business_record_import', true, NULL, now()),
  ('ENTERPRISE', 'reports.exports', true, NULL, now()),
  ('ENTERPRISE', 'invoice.monthly_limit', NULL, NULL, now()),
  ('ENTERPRISE', 'users.max', NULL, NULL, now()),
  ('ENTERPRISE', 'storage.max_bytes', NULL, NULL, now());--> statement-breakpoint
INSERT INTO "organizations" ("id", "name", "created_at") VALUES
  ('00000000000000000000000000', 'Veyra Operations', now())
  ON CONFLICT ("id") DO NOTHING;--> statement-breakpoint
UPDATE "organizations" SET "plan_key" = 'ENTERPRISE', "plan_assigned_at" = now()
  WHERE "id" <> '00000000000000000000000000' AND "plan_key" IS NULL;
