CREATE TABLE "erp_receipt_records" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "erp_receipt_records_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"invoice_no_key" text NOT NULL,
	"vendor_name" text NOT NULL,
	"grn_no" text NOT NULL,
	"record_json" text NOT NULL,
	"attachment_name" text,
	"attachment_base64" text,
	"source_filename" text NOT NULL,
	"imported_by_user_id" text NOT NULL,
	"imported_at" timestamp(3) with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "erp_receipt_records" ADD CONSTRAINT "erp_receipt_records_imported_by_user_id_users_id_fk" FOREIGN KEY ("imported_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "erp_receipt_records_invoice" ON "erp_receipt_records" USING btree ("invoice_no_key");