CREATE TABLE "processing_usage" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "processing_usage_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"extraction_id" text NOT NULL,
	"invoice_id" text NOT NULL,
	"method" text NOT NULL,
	"pages" integer NOT NULL,
	"ai_model" text,
	"ai_calls" integer NOT NULL,
	"ai_input_tokens" bigint NOT NULL,
	"ai_output_tokens" bigint NOT NULL,
	"duration_ms" integer,
	"document_bytes" bigint NOT NULL,
	"created_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "processing_usage_extraction_id_unique" UNIQUE("extraction_id")
);
--> statement-breakpoint
ALTER TABLE "commercial_events" DROP CONSTRAINT "commercial_events_event";--> statement-breakpoint
ALTER TABLE "organizations" DROP CONSTRAINT "organizations_commercial_status";--> statement-breakpoint
ALTER TABLE "commercial_events" ADD COLUMN "subject" text;--> statement-breakpoint
ALTER TABLE "plans" ADD COLUMN "price_monthly_paise" bigint;--> statement-breakpoint
CREATE INDEX "processing_usage_created" ON "processing_usage" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "processing_usage_invoice" ON "processing_usage" USING btree ("invoice_id");--> statement-breakpoint
ALTER TABLE "commercial_events" ADD CONSTRAINT "commercial_events_event" CHECK ("commercial_events"."event" IN ('plan.assigned', 'plan.entitlement_changed', 'override.set', 'override.removed', 'plan.price_changed', 'organization.suspended', 'organization.reactivated', 'user.disabled', 'user.enabled', 'processing.retried', 'config.changed'));--> statement-breakpoint
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_commercial_status" CHECK ("organizations"."commercial_status" IN ('trial', 'active', 'suspended'));