CREATE TABLE "blog_article_tags" (
	"article_id" text NOT NULL,
	"tag_id" text NOT NULL,
	CONSTRAINT "blog_article_tags_article_id_tag_id_pk" PRIMARY KEY("article_id","tag_id")
);
--> statement-breakpoint
CREATE TABLE "blog_articles" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "blog_articles_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"excerpt" text DEFAULT '' NOT NULL,
	"body_json" text DEFAULT '[]' NOT NULL,
	"faq_json" text DEFAULT '[]' NOT NULL,
	"status" text NOT NULL,
	"author_id" text,
	"category_id" text,
	"seo_title" text,
	"meta_description" text,
	"canonical_url" text,
	"noindex" boolean DEFAULT false NOT NULL,
	"og_title" text,
	"og_description" text,
	"og_image_id" text,
	"twitter_card" text DEFAULT 'summary_large_image' NOT NULL,
	"focus_keyword" text,
	"featured_media_id" text,
	"featured_alt" text,
	"cta" text DEFAULT 'challenge' NOT NULL,
	"search_text" text DEFAULT '' NOT NULL,
	"word_count" integer DEFAULT 0 NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"published_at" timestamp(3) with time zone,
	"first_published_at" timestamp(3) with time zone,
	"content_updated_at" timestamp(3) with time zone,
	"created_by" text,
	"updated_by" text,
	"created_at" timestamp(3) with time zone NOT NULL,
	"updated_at" timestamp(3) with time zone NOT NULL,
	"deleted_at" timestamp(3) with time zone,
	CONSTRAINT "blog_articles_slug_unique" UNIQUE("slug"),
	CONSTRAINT "blog_articles_status" CHECK ("blog_articles"."status" IN ('DRAFT', 'IN_REVIEW', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED')),
	CONSTRAINT "blog_articles_cta" CHECK ("blog_articles"."cta" IN ('challenge', 'demo', 'none')),
	CONSTRAINT "blog_articles_twitter_card" CHECK ("blog_articles"."twitter_card" IN ('summary_large_image', 'summary')),
	CONSTRAINT "blog_articles_dated" CHECK ("blog_articles"."status" NOT IN ('SCHEDULED', 'PUBLISHED') OR "blog_articles"."published_at" IS NOT NULL),
	CONSTRAINT "blog_articles_version" CHECK ("blog_articles"."version" >= 1)
);
--> statement-breakpoint
CREATE TABLE "blog_authors" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "blog_authors_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"role_title" text DEFAULT '' NOT NULL,
	"bio" text DEFAULT '' NOT NULL,
	"created_at" timestamp(3) with time zone NOT NULL,
	"updated_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "blog_authors_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "blog_categories" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "blog_categories_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp(3) with time zone NOT NULL,
	"updated_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "blog_categories_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "blog_events" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "blog_events_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"event" text NOT NULL,
	"article_id" text,
	"user_id" text,
	"detail_json" text NOT NULL,
	"created_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "blog_events_event" CHECK ("blog_events"."event" IN ('article.created', 'article.updated', 'article.duplicated', 'article.status', 'article.slug_changed', 'article.restored', 'article.deleted', 'media.uploaded', 'media.deleted', 'taxonomy.changed', 'author.changed', 'redirect.changed'))
);
--> statement-breakpoint
CREATE TABLE "blog_media" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "blog_media_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"mime" text NOT NULL,
	"body" "bytea" NOT NULL,
	"width" integer NOT NULL,
	"height" integer NOT NULL,
	"bytes" integer NOT NULL,
	"small_body" "bytea",
	"small_width" integer,
	"sha256" text NOT NULL,
	"alt" text DEFAULT '' NOT NULL,
	"created_by" text,
	"created_at" timestamp(3) with time zone NOT NULL,
	"deleted_at" timestamp(3) with time zone,
	CONSTRAINT "blog_media_mime" CHECK ("blog_media"."mime" IN ('image/webp', 'image/jpeg', 'image/png'))
);
--> statement-breakpoint
CREATE TABLE "blog_redirects" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "blog_redirects_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"from_path" text NOT NULL,
	"to_path" text NOT NULL,
	"article_id" text,
	"hits" integer DEFAULT 0 NOT NULL,
	"created_by" text,
	"created_at" timestamp(3) with time zone NOT NULL,
	"removed_at" timestamp(3) with time zone,
	CONSTRAINT "blog_redirects_paths" CHECK ("blog_redirects"."from_path" <> "blog_redirects"."to_path")
);
--> statement-breakpoint
CREATE TABLE "blog_revisions" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "blog_revisions_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"article_id" text NOT NULL,
	"version" integer NOT NULL,
	"status" text NOT NULL,
	"snapshot_json" text NOT NULL,
	"reason" text NOT NULL,
	"created_by" text,
	"created_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "blog_revisions_status" CHECK ("blog_revisions"."status" IN ('DRAFT', 'IN_REVIEW', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED'))
);
--> statement-breakpoint
CREATE TABLE "blog_tags" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "blog_tags_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"created_at" timestamp(3) with time zone NOT NULL,
	"updated_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "blog_tags_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "blog_article_tags" ADD CONSTRAINT "blog_article_tags_article_id_blog_articles_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."blog_articles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blog_article_tags" ADD CONSTRAINT "blog_article_tags_tag_id_blog_tags_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."blog_tags"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blog_articles" ADD CONSTRAINT "blog_articles_author_id_blog_authors_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."blog_authors"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blog_articles" ADD CONSTRAINT "blog_articles_category_id_blog_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."blog_categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blog_articles" ADD CONSTRAINT "blog_articles_og_image_id_blog_media_id_fk" FOREIGN KEY ("og_image_id") REFERENCES "public"."blog_media"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blog_articles" ADD CONSTRAINT "blog_articles_featured_media_id_blog_media_id_fk" FOREIGN KEY ("featured_media_id") REFERENCES "public"."blog_media"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blog_articles" ADD CONSTRAINT "blog_articles_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blog_articles" ADD CONSTRAINT "blog_articles_updated_by_users_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blog_events" ADD CONSTRAINT "blog_events_article_id_blog_articles_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."blog_articles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blog_events" ADD CONSTRAINT "blog_events_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blog_media" ADD CONSTRAINT "blog_media_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blog_redirects" ADD CONSTRAINT "blog_redirects_article_id_blog_articles_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."blog_articles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blog_redirects" ADD CONSTRAINT "blog_redirects_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blog_revisions" ADD CONSTRAINT "blog_revisions_article_id_blog_articles_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."blog_articles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blog_revisions" ADD CONSTRAINT "blog_revisions_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "blog_article_tags_tag" ON "blog_article_tags" USING btree ("tag_id");--> statement-breakpoint
CREATE INDEX "blog_articles_public" ON "blog_articles" USING btree ("status","published_at");--> statement-breakpoint
CREATE INDEX "blog_articles_category" ON "blog_articles" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "blog_articles_author" ON "blog_articles" USING btree ("author_id");--> statement-breakpoint
CREATE INDEX "blog_events_article" ON "blog_events" USING btree ("article_id");--> statement-breakpoint
CREATE UNIQUE INDEX "blog_media_sha256" ON "blog_media" USING btree ("sha256");--> statement-breakpoint
CREATE UNIQUE INDEX "blog_redirects_active" ON "blog_redirects" USING btree ("from_path") WHERE "blog_redirects"."removed_at" IS NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "blog_revisions_version" ON "blog_revisions" USING btree ("article_id","version");