CREATE TABLE "data_sources" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "data_sources_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text PRIMARY KEY NOT NULL,
	"kind" text NOT NULL,
	"name" text NOT NULL,
	"spreadsheet_id" text,
	"sheet_title" text NOT NULL,
	"header_row" integer NOT NULL,
	"mapping_json" text NOT NULL,
	"header_signature" text NOT NULL,
	"enabled" boolean NOT NULL,
	"last_synced_at" timestamp(3) with time zone,
	"last_sync_status" text,
	"last_sync_summary_json" text,
	"created_by_user_id" text NOT NULL,
	"created_at" timestamp(3) with time zone NOT NULL,
	CONSTRAINT "data_sources_kind" CHECK ("data_sources"."kind" IN ('upload', 'google_sheet')),
	CONSTRAINT "data_sources_google_id" CHECK (("data_sources"."kind" = 'google_sheet') = ("data_sources"."spreadsheet_id" IS NOT NULL)),
	CONSTRAINT "data_sources_status" CHECK ("data_sources"."last_sync_status" IS NULL OR "data_sources"."last_sync_status" IN ('ok', 'failed', 'columns_changed'))
);
--> statement-breakpoint
ALTER TABLE "erp_receipt_records" ADD COLUMN "source_id" text;--> statement-breakpoint
ALTER TABLE "data_sources" ADD CONSTRAINT "data_sources_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "erp_receipt_records" ADD CONSTRAINT "erp_receipt_records_source_id_data_sources_id_fk" FOREIGN KEY ("source_id") REFERENCES "public"."data_sources"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- The spreadsheet-register capability, granted like business-record imports (Business and up).
INSERT INTO "plan_entitlements" ("plan_key", "capability", "enabled", "limit_value", "updated_at") VALUES
  ('STARTER', 'erp.spreadsheet_sources', false, NULL, now()),
  ('BUSINESS', 'erp.spreadsheet_sources', true, NULL, now()),
  ('ENTERPRISE', 'erp.spreadsheet_sources', true, NULL, now())
  ON CONFLICT DO NOTHING;
