import { sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  check,
  customType,
  index,
  integer,
  pgTable,
  primaryKey,
  text,
  uniqueIndex,
  type AnyPgColumn,
} from 'drizzle-orm/pg-core';
import {
  AUDIT_ACTOR_TYPES,
  COMMERCIAL_EVENTS,
  COMMERCIAL_STATUSES,
  PLAN_STATUSES,
  CREATION_ACTION_STATUSES,
  CREATION_ENTITIES,
  CREATION_TRIGGERS,
  EXTRACTION_METHODS,
  FIELD_SOURCES,
  INVOICE_STATES,
  JOB_STATUSES,
  JOB_TYPES,
  DOCUMENT_RETENTION_MODES,
  DOCUMENT_STATUSES,
  MATCH_ENTITIES,
  MATCH_OUTCOMES,
  QUESTION_KINDS,
  QUESTION_STATUSES,
  SECURITY_EVENTS,
  VALIDATION_OUTCOMES,
} from '@veyra/shared';

/** What Veyra knows about one ERP write (see `erpWrites`). */
export const ERP_WRITE_STATUSES = [
  'pending',
  'confirmed',
  'not_created',
  'unknown',
  'failed',
] as const;
export type ErpWriteStatus = (typeof ERP_WRITE_STATUSES)[number];

/**
 * The Veyra application database (ARCHITECTURE §4.2, §19), PostgreSQL. Veyra's own workflow data;
 * ERP records live behind ErpConnector.
 *
 * - Ids are ULIDs generated by Veyra (text), as before.
 * - Instants (created/updated/answered/locked…) are `timestamp(3) with time zone`, read and
 *   written as ISO-8601 UTC strings (`isoTimestamp`). There are no business-date columns: invoice
 *   and receipt dates live inside the validated JSON as YYYY-MM-DD and are never converted.
 * - Money, quantities and rates never appear as columns: they live inside Zod-validated JSON
 *   (field values, staged payloads) as integers. JSON is kept as text, byte for byte.
 * - `seq` (an identity column) records insertion order, which SQLite provided through rowid and
 *   the audit trail, questions and checks are listed in. ULIDs alone do not give it.
 */

const inList = (col: AnyPgColumn, values: readonly string[]) =>
  sql`${col} IN (${sql.raw(values.map((v) => `'${v}'`).join(', '))})`;

/** PostgreSQL output (`2026-09-28 06:30:00.123+00`, or a Date) → `2026-09-28T06:30:00.123Z`. */
export function toIsoTimestamp(value: string | Date): string {
  if (value instanceof Date) return value.toISOString();
  const m = /^(\d{4}-\d{2}-\d{2})[ T](\d{2}:\d{2}:\d{2}(?:\.\d+)?)(Z|[+-]\d{2}(?::?\d{2})?)$/.exec(
    value,
  );
  const [, date, time, offset] = m ?? [];
  if (!date || !time || !offset) throw new Error('unexpected timestamp format from the database');
  const zone =
    offset === 'Z'
      ? 'Z'
      : offset.length === 3
        ? `${offset}:00`
        : offset.replace(/^([+-]\d{2}):?(\d{2})$/, '$1:$2');
  return new Date(`${date}T${time}${zone}`).toISOString();
}

/** An instant, stored as timestamptz with millisecond precision, exchanged as an ISO string. */
const isoTimestamp = customType<{ data: string; driverData: string | Date }>({
  dataType: () => 'timestamp(3) with time zone',
  toDriver: (value) => value,
  fromDriver: (value) => toIsoTimestamp(value),
});

/** Insertion order (SQLite's rowid). Assigned by the database. */
const seq = () => bigint('seq', { mode: 'number' }).generatedByDefaultAsIdentity();

/**
 * The organization this deployment serves (Phase 6C). Exactly one today (the configured customer);
 * every user belongs to it, and authorization runs user → organization → resource, so more than
 * one organization later does not mean rewriting access checks. Not multi-tenancy.
 */
export const organizations = pgTable(
  'organizations',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    createdAt: isoTimestamp('created_at').notNull(),
    /**
     * The commercial plan (Phase 8A). Null only for Veyra's own platform organization, which is
     * not a customer. Assigned and changed only through Veyra Operations (audited).
     */
    planKey: text('plan_key').references((): AnyPgColumn => plans.key),
    planAssignedAt: isoTimestamp('plan_assigned_at'),
    commercialStatus: text('commercial_status').notNull().default('active'),
  },
  (t) => [
    check('organizations_commercial_status', inList(t.commercialStatus, COMMERCIAL_STATUSES)),
  ],
);

/**
 * Veyra's own organization (Phase 8A): holds the VEYRA_ADMIN accounts, and nothing else. It is not
 * a customer; customer routes refuse its users, and its users are the only ones Veyra Operations
 * accepts.
 */
export const PLATFORM_ORGANIZATION_ID = '00000000000000000000000000';

/** People who can sign in (Phase 6C adds role, password hash, organization). */
export const USER_ROLES = ['ADMIN', 'FINANCE', 'REVIEWER', 'VEYRA_ADMIN'] as const;
export type UserRole = (typeof USER_ROLES)[number];

export const users = pgTable(
  'users',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    /** Always lower case. */
    email: text('email').notNull().unique(),
    active: boolean('active').notNull(),
    organizationId: text('organization_id')
      .notNull()
      .references(() => organizations.id),
    role: text('role').notNull(),
    /** Argon2id (PHC string). Null: the account cannot sign in with a password. */
    passwordHash: text('password_hash'),
    passwordChangedAt: isoTimestamp('password_changed_at'),
    createdAt: isoTimestamp('created_at').notNull(),
    updatedAt: isoTimestamp('updated_at').notNull(),
  },
  (t) => [
    check('users_role', inList(t.role, USER_ROLES)),
    // Platform accounts live only in the platform organization, and customer accounts never do.
    check(
      'users_platform_role',
      sql`(${t.role} = 'VEYRA_ADMIN') = (${t.organizationId} = '${sql.raw(PLATFORM_ORGANIZATION_ID)}')`,
    ),
    check('users_email_lower', sql`${t.email} = lower(${t.email})`),
  ],
);

/**
 * Server-side sessions (Phase 6C). The browser holds a random token in an HttpOnly cookie; only its
 * SHA-256 is stored here, so a copy of the database does not give usable sessions.
 */
export const sessions = pgTable(
  'sessions',
  {
    seq: seq(),
    tokenHash: text('token_hash').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id),
    /** Synchronizer token: state-changing requests must echo it in a header (CSRF). */
    csrfToken: text('csrf_token').notNull(),
    createdAt: isoTimestamp('created_at').notNull(),
    lastSeenAt: isoTimestamp('last_seen_at').notNull(),
    /** Absolute end of the session, whatever the activity. */
    expiresAt: isoTimestamp('expires_at').notNull(),
    revokedAt: isoTimestamp('revoked_at'),
  },
  (t) => [index('sessions_user').on(t.userId)],
);

/**
 * Security audit trail (Phase 6C): sign-ins, sign-outs, user changes, denied access and document
 * access. Separate from `audit_events`, the invoice workflow's trail. Never holds passwords,
 * tokens, cookies or document contents; `detail_json` carries opaque ids and codes only.
 */
export const securityEvents = pgTable(
  'security_events',
  {
    seq: seq(),
    id: text('id').primaryKey(),
    event: text('event').notNull(),
    /** Who acted (null: nobody signed in, e.g. a failed sign-in for an unknown account). */
    userId: text('user_id').references(() => users.id),
    /** The account acted upon (user administration, a failed sign-in for a known account). */
    subjectUserId: text('subject_user_id').references(() => users.id),
    requestId: text('request_id'),
    detailJson: text('detail_json').notNull(),
    createdAt: isoTimestamp('created_at').notNull(),
  },
  (t) => [
    check('security_events_event', inList(t.event, SECURITY_EVENTS)),
    index('security_events_created').on(t.createdAt),
  ],
);

export const settings = pgTable('settings', {
  key: text('key').primaryKey(),
  valueJson: text('value_json').notNull(),
  updatedByUserId: text('updated_by_user_id').references(() => users.id),
  updatedAt: isoTimestamp('updated_at').notNull(),
});

export const documents = pgTable(
  'documents',
  {
    seq: seq(),
    id: text('id').primaryKey(),
    sha256: text('sha256').notNull().unique(),
    filename: text('filename').notNull(),
    mime: text('mime').notNull(),
    sizeBytes: integer('size_bytes').notNull(),
    storagePath: text('storage_path').notNull(),
    uploadedByUserId: text('uploaded_by_user_id')
      .notNull()
      .references(() => users.id),
    uploadedAt: isoTimestamp('uploaded_at').notNull(),
    /** AVAILABLE, or DELETED: the file is gone; the invoice record and audit trail stay. */
    status: text('status').notNull().default('AVAILABLE'),
    deletedAt: isoTimestamp('deleted_at'),
    /**
     * The retention policy in force when the document was uploaded (a later change of policy never
     * applies to it). Null for documents uploaded before retention existed: kept.
     */
    retentionMode: text('retention_mode'),
    retentionDays: integer('retention_days'),
  },
  (t) => [
    check('documents_status', inList(t.status, DOCUMENT_STATUSES)),
    // NULL passes a CHECK: documents from before retention existed.
    check('documents_retention_mode', inList(t.retentionMode, DOCUMENT_RETENTION_MODES)),
    check('documents_mime', inList(t.mime, ['application/pdf', 'image/jpeg', 'image/png'])),
    check('documents_size', sql`${t.sizeBytes} > 0`),
    // Phase 8A: invoices uploaded this month (the commercial monthly limit and usage).
    index('documents_uploaded').on(t.uploadedAt),
  ],
);

export const invoices = pgTable(
  'invoices',
  {
    seq: seq(),
    id: text('id').primaryKey(),
    documentId: text('document_id')
      .notNull()
      .unique()
      .references(() => documents.id),
    state: text('state').notNull(),
    /** Optimistic lock: every transition bumps it. */
    stateVersion: integer('state_version').notNull(),
    /** Number of the latest MATCHING → VALIDATING run. */
    runNo: integer('run_no').notNull(),
    vendorErpId: text('vendor_erp_id'),
    poErpId: text('po_erp_id'),
    erpPurchaseInvoiceId: text('erp_purchase_invoice_id'),
    /** Business duplicate key (RULES R11), set once the fields are usable. */
    dupVendorGstin: text('dup_vendor_gstin'),
    dupInvoiceNo: text('dup_invoice_no'),
    dupFy: text('dup_fy'),
    /** The frozen plan COMMITTING executes (and resumes after a crash). */
    commitPlanJson: text('commit_plan_json'),
    failedStage: text('failed_stage'),
    failureReason: text('failure_reason'),
    rejectedByUserId: text('rejected_by_user_id').references(() => users.id),
    rejectedReason: text('rejected_reason'),
    createdAt: isoTimestamp('created_at').notNull(),
    updatedAt: isoTimestamp('updated_at').notNull(),
  },
  (t) => [
    check('invoices_state', inList(t.state, INVOICE_STATES)),
    index('invoices_dup').on(t.dupVendorGstin, t.dupInvoiceNo, t.dupFy),
  ],
);

export const extractions = pgTable(
  'extractions',
  {
    seq: seq(),
    id: text('id').primaryKey(),
    invoiceId: text('invoice_id')
      .notNull()
      .references(() => invoices.id),
    extractorId: text('extractor_id').notNull(),
    extractorVersion: text('extractor_version').notNull(),
    rawJson: text('raw_json').notNull(),
    createdAt: isoTimestamp('created_at').notNull(),
  },
  // Phase 7: an invoice's latest reading (the invoice detail).
  (t) => [index('extractions_invoice').on(t.invoiceId, t.createdAt)],
);

export const extractedFields = pgTable(
  'extracted_fields',
  {
    seq: seq(),
    id: text('id').primaryKey(),
    invoiceId: text('invoice_id')
      .notNull()
      .references(() => invoices.id),
    path: text('path').notNull(),
    valueJson: text('value_json').notNull(),
    confidenceBp: integer('confidence_bp'),
    evidenceJson: text('evidence_json'),
    evidenceDetailJson: text('evidence_detail_json'),
    source: text('source').notNull(),
    /** How an extracted value was read (pdf_text, tesseract, ollama, fixture); null otherwise. */
    method: text('method'),
    extractionId: text('extraction_id').references(() => extractions.id),
    updatedByUserId: text('updated_by_user_id').references(() => users.id),
    updatedAt: isoTimestamp('updated_at').notNull(),
  },
  (t) => [
    uniqueIndex('extracted_fields_path').on(t.invoiceId, t.path),
    check('extracted_fields_source', inList(t.source, FIELD_SOURCES)),
    check(
      'extracted_fields_method',
      sql`${t.method} IS NULL OR ${inList(t.method, EXTRACTION_METHODS)}`,
    ),
    check(
      'extracted_fields_confidence',
      sql`${t.confidenceBp} IS NULL OR ${t.confidenceBp} BETWEEN 0 AND 10000`,
    ),
    check(
      'extracted_fields_human',
      sql`${t.source} NOT IN ('human_confirmed', 'human_corrected') OR ${t.updatedByUserId} IS NOT NULL`,
    ),
  ],
);

export const invoiceLines = pgTable(
  'invoice_lines',
  {
    seq: seq(),
    id: text('id').primaryKey(),
    invoiceId: text('invoice_id')
      .notNull()
      .references(() => invoices.id),
    lineNo: integer('line_no').notNull(),
    itemErpId: text('item_erp_id'),
    poLineErpId: text('po_line_erp_id'),
    itemRefStagedActionId: text('item_ref_staged_action_id'),
  },
  (t) => [uniqueIndex('invoice_lines_no').on(t.invoiceId, t.lineNo)],
);

export const matchResults = pgTable(
  'match_results',
  {
    seq: seq(),
    id: text('id').primaryKey(),
    invoiceId: text('invoice_id')
      .notNull()
      .references(() => invoices.id),
    runNo: integer('run_no').notNull(),
    entity: text('entity').notNull(),
    lineNo: integer('line_no'),
    outcome: text('outcome').notNull(),
    method: text('method').notNull(),
    candidatesJson: text('candidates_json').notNull(),
    chosenErpId: text('chosen_erp_id'),
  },
  (t) => [
    check('match_results_entity', inList(t.entity, MATCH_ENTITIES)),
    check('match_results_outcome', inList(t.outcome, MATCH_OUTCOMES)),
    index('match_results_run').on(t.invoiceId, t.runNo),
  ],
);

export const creationActions = pgTable(
  'creation_actions',
  {
    seq: seq(),
    id: text('id').primaryKey(),
    invoiceId: text('invoice_id')
      .notNull()
      .references(() => invoices.id),
    entity: text('entity').notNull(),
    payloadJson: text('payload_json').notNull(),
    /** Deterministic identity of what is staged, so a re-run reuses the same action. */
    signature: text('signature').notNull(),
    policyCode: text('policy_code').notNull(),
    trigger: text('trigger').notNull(),
    approvedByUserId: text('approved_by_user_id').references(() => users.id),
    questionId: text('question_id'),
    status: text('status').notNull(),
    erpId: text('erp_id'),
    idempotencyKey: text('idempotency_key').notNull().unique(),
    createdAt: isoTimestamp('created_at').notNull(),
    committedAt: isoTimestamp('committed_at'),
  },
  (t) => [
    check('creation_actions_entity', inList(t.entity, CREATION_ENTITIES)),
    check('creation_actions_trigger', inList(t.trigger, CREATION_TRIGGERS)),
    check('creation_actions_status', inList(t.status, CREATION_ACTION_STATUSES)),
    check(
      'creation_actions_committed',
      sql`(${t.status} = 'committed') = (${t.erpId} IS NOT NULL AND ${t.committedAt} IS NOT NULL)`,
    ),
    check(
      'creation_actions_approval',
      sql`${t.trigger} <> 'user_approval' OR (${t.approvedByUserId} IS NOT NULL AND ${t.questionId} IS NOT NULL)`,
    ),
    check(
      'creation_actions_no_auto_grn_or_item',
      sql`${t.entity} NOT IN ('grn', 'item', 'vendor_reactivation') OR ${t.trigger} = 'user_approval'`,
    ),
    index('creation_actions_invoice').on(t.invoiceId, t.status),
  ],
);

export const validationResults = pgTable(
  'validation_results',
  {
    seq: seq(),
    id: text('id').primaryKey(),
    invoiceId: text('invoice_id')
      .notNull()
      .references(() => invoices.id),
    runNo: integer('run_no').notNull(),
    ruleCode: text('rule_code').notNull(),
    lineNo: integer('line_no'),
    outcome: text('outcome').notNull(),
    naReason: text('na_reason'),
    expectedJson: text('expected_json').notNull(),
    actualJson: text('actual_json').notNull(),
    message: text('message').notNull(),
    createdAt: isoTimestamp('created_at').notNull(),
  },
  (t) => [
    check('validation_results_outcome', inList(t.outcome, VALIDATION_OUTCOMES)),
    check(
      'validation_results_na',
      sql`(${t.outcome} = 'not_applicable') = (${t.naReason} IS NOT NULL)`,
    ),
    index('validation_results_run').on(t.invoiceId, t.runNo),
  ],
);

export const questions = pgTable(
  'questions',
  {
    seq: seq(),
    id: text('id').primaryKey(),
    invoiceId: text('invoice_id')
      .notNull()
      .references(() => invoices.id),
    kind: text('kind').notNull(),
    code: text('code').notNull(),
    subjectKey: text('subject_key').notNull(),
    prompt: text('prompt').notNull(),
    contextJson: text('context_json').notNull(),
    optionsJson: text('options_json').notNull(),
    inputSchemaJson: text('input_schema_json'),
    status: text('status').notNull(),
    assignedToUserId: text('assigned_to_user_id')
      .notNull()
      .references(() => users.id),
    answerJson: text('answer_json'),
    answeredByUserId: text('answered_by_user_id').references(() => users.id),
    answeredAt: isoTimestamp('answered_at'),
    /** Global order of answers, so "the latest decision" is unambiguous. */
    answerSeq: integer('answer_seq'),
    createdAt: isoTimestamp('created_at').notNull(),
  },
  (t) => [
    check('questions_kind', inList(t.kind, QUESTION_KINDS)),
    check('questions_status', inList(t.status, QUESTION_STATUSES)),
    check(
      'questions_answer',
      sql`(${t.status} = 'answered') = (${t.answerJson} IS NOT NULL AND ${t.answeredByUserId} IS NOT NULL AND ${t.answeredAt} IS NOT NULL AND ${t.answerSeq} IS NOT NULL)`,
    ),
    uniqueIndex('questions_open_subject')
      .on(t.invoiceId, t.code, t.subjectKey)
      .where(sql`${t.status} = 'open'`),
    // Phase 7 (docs/PERFORMANCE.md "Database"): an invoice's questions (detail, list views,
    // every engine run), and the open-question queue, without scanning every question ever asked.
    index('questions_invoice').on(t.invoiceId, t.seq),
    index('questions_open')
      .on(t.seq)
      .where(sql`${t.status} = 'open'`),
  ],
);

/**
 * Every ERP write Veyra makes for an invoice (Phase 4): the explicit link between a Veyra
 * invoice and the ERP's record (`erp_id`, opaque, and the ERP's own reference such as an invoice
 * or receipt number), and what Veyra knows about the write. `pending` is recorded before the call
 * (write-ahead); `unknown` means the response was lost and the write must be reconciled, never
 * re-sent as a new transaction.
 */
export const erpWrites = pgTable(
  'erp_writes',
  {
    seq: seq(),
    idempotencyKey: text('idempotency_key').primaryKey(),
    invoiceId: text('invoice_id')
      .notNull()
      .references(() => invoices.id),
    operation: text('operation').notNull(),
    status: text('status').notNull(),
    erpId: text('erp_id'),
    externalRef: text('external_ref'),
    errorCode: text('error_code'),
    createdAt: isoTimestamp('created_at').notNull(),
    updatedAt: isoTimestamp('updated_at').notNull(),
  },
  (t) => [
    index('erp_writes_invoice').on(t.invoiceId),
    check('erp_writes_status', inList(t.status, ERP_WRITE_STATUSES)),
    check('erp_writes_confirmed', sql`${t.status} <> 'confirmed' OR ${t.erpId} IS NOT NULL`),
  ],
);

export const auditEvents = pgTable(
  'audit_events',
  {
    seq: seq(),
    id: text('id').primaryKey(),
    invoiceId: text('invoice_id').references(() => invoices.id),
    actorType: text('actor_type').notNull(),
    actorUserId: text('actor_user_id').references(() => users.id),
    event: text('event').notNull(),
    fromState: text('from_state'),
    toState: text('to_state'),
    detailJson: text('detail_json').notNull(),
    createdAt: isoTimestamp('created_at').notNull(),
  },
  (t) => [
    check('audit_events_actor', inList(t.actorType, AUDIT_ACTOR_TYPES)),
    check('audit_events_user', sql`(${t.actorType} = 'user') = (${t.actorUserId} IS NOT NULL)`),
    index('audit_events_invoice').on(t.invoiceId),
  ],
);

export const jobs = pgTable(
  'jobs',
  {
    seq: seq(),
    id: text('id').primaryKey(),
    invoiceId: text('invoice_id')
      .notNull()
      .references(() => invoices.id),
    type: text('type').notNull(),
    status: text('status').notNull(),
    attempts: integer('attempts').notNull(),
    runAfter: isoTimestamp('run_after').notNull(),
    lockedAt: isoTimestamp('locked_at'),
    lastError: text('last_error'),
    createdAt: isoTimestamp('created_at').notNull(),
    updatedAt: isoTimestamp('updated_at').notNull(),
  },
  (t) => [
    check('jobs_type', inList(t.type, JOB_TYPES)),
    check('jobs_status', inList(t.status, JOB_STATUSES)),
    index('jobs_queue').on(t.status, t.runAfter),
    // Phase 7: an invoice's jobs (processing status in the detail and readiness).
    index('jobs_invoice').on(t.invoiceId, t.createdAt),
  ],
);

/**
 * Business-record imports (Phase 3C). The uploaded files are kept (storage dir) so a confirmation
 * re-validates against the ERP as it is at that moment. Records themselves live in the ERP.
 */
/**
 * Goods-receipt records exported by the business's own ERP (its JSON API), imported for the
 * receipt check: an invoice whose number and supplier match one is compared with it value by
 * value. Kept as the ERP sent them (`recordJson`), with the attached invoice PDF if any.
 */
export const erpReceiptRecords = pgTable(
  'erp_receipt_records',
  {
    seq: seq(),
    id: text('id').primaryKey(),
    /** The supplier's invoice number as the ERP holds it, normalised for matching. */
    invoiceNoKey: text('invoice_no_key').notNull(),
    vendorName: text('vendor_name').notNull(),
    grnNo: text('grn_no').notNull(),
    recordJson: text('record_json').notNull(),
    attachmentName: text('attachment_name'),
    attachmentBase64: text('attachment_base64'),
    sourceFilename: text('source_filename').notNull(),
    importedByUserId: text('imported_by_user_id')
      .notNull()
      .references(() => users.id),
    importedAt: isoTimestamp('imported_at').notNull(),
  },
  (t) => [index('erp_receipt_records_invoice').on(t.invoiceNoKey)],
);

export const imports = pgTable(
  'imports',
  {
    seq: seq(),
    id: text('id').primaryKey(),
    filesJson: text('files_json').notNull(),
    kinds: text('kinds').notNull(),
    status: text('status').notNull(),
    checkJson: text('check_json').notNull(),
    resultJson: text('result_json'),
    uploadedByUserId: text('uploaded_by_user_id')
      .notNull()
      .references(() => users.id),
    confirmedByUserId: text('confirmed_by_user_id').references(() => users.id),
    createdAt: isoTimestamp('created_at').notNull(),
    confirmedAt: isoTimestamp('confirmed_at'),
  },
  (t) => [
    check('imports_status', inList(t.status, ['ready', 'invalid', 'imported'])),
    check(
      'imports_confirmed',
      sql`(${t.status} = 'imported') = (${t.resultJson} IS NOT NULL AND ${t.confirmedAt} IS NOT NULL AND ${t.confirmedByUserId} IS NOT NULL)`,
    ),
  ],
);

// ── Commercial entitlements (Phase 8A, docs/COMMERCIAL_ENTITLEMENTS.md) ─────

/**
 * A commercial plan: a named set of entitlements. The optional monthly price is for Veyrafy's own
 * MRR figure only; there is no billing or payment.
 */
export const plans = pgTable(
  'plans',
  {
    key: text('key').primaryKey(),
    name: text('name').notNull(),
    status: text('status').notNull(),
    description: text('description').notNull(),
    priceMonthlyPaise: bigint('price_monthly_paise', { mode: 'number' }),
    createdAt: isoTimestamp('created_at').notNull(),
    updatedAt: isoTimestamp('updated_at').notNull(),
  },
  (t) => [check('plans_status', inList(t.status, PLAN_STATUSES))],
);

/**
 * What a plan includes, per capability key (packages/shared/src/commercial.ts). A BOOLEAN capability
 * has `enabled`; a LIMIT has `limit_value` (NULL = unlimited). A capability without a row is not
 * included.
 */
export const planEntitlements = pgTable(
  'plan_entitlements',
  {
    planKey: text('plan_key')
      .notNull()
      .references(() => plans.key),
    capability: text('capability').notNull(),
    enabled: boolean('enabled'),
    limitValue: bigint('limit_value', { mode: 'number' }),
    updatedAt: isoTimestamp('updated_at').notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.planKey, t.capability] }),
    check('plan_entitlements_one_kind', sql`${t.enabled} IS NULL OR ${t.limitValue} IS NULL`),
    check('plan_entitlements_limit', sql`${t.limitValue} IS NULL OR ${t.limitValue} >= 0`),
  ],
);

/**
 * A customer-specific exception to its plan: enable a beta feature, raise a negotiated quota,
 * switch something off. Never edited in place: a change revokes the active row and inserts a new
 * one, so the history stays. At most one active (unrevoked) row per organization and capability;
 * `expires_at` makes it temporary: once past, the plan applies again, with no clean-up job needed.
 */
export const entitlementOverrides = pgTable(
  'entitlement_overrides',
  {
    seq: seq(),
    id: text('id').primaryKey(),
    organizationId: text('organization_id')
      .notNull()
      .references(() => organizations.id),
    capability: text('capability').notNull(),
    enabled: boolean('enabled'),
    limitValue: bigint('limit_value', { mode: 'number' }),
    /** A LIMIT override to "unlimited" (limit_value is then NULL). */
    unlimited: boolean('unlimited').notNull().default(false),
    reason: text('reason').notNull(),
    expiresAt: isoTimestamp('expires_at'),
    createdByUserId: text('created_by_user_id')
      .notNull()
      .references(() => users.id),
    createdAt: isoTimestamp('created_at').notNull(),
    revokedAt: isoTimestamp('revoked_at'),
    revokedByUserId: text('revoked_by_user_id').references(() => users.id),
  },
  (t) => [
    uniqueIndex('entitlement_overrides_active')
      .on(t.organizationId, t.capability)
      .where(sql`${t.revokedAt} IS NULL`),
    check(
      'entitlement_overrides_one_kind',
      sql`(${t.enabled} IS NOT NULL) <> (${t.limitValue} IS NOT NULL OR ${t.unlimited})`,
    ),
    check('entitlement_overrides_limit', sql`${t.limitValue} IS NULL OR ${t.limitValue} >= 0`),
    check('entitlement_overrides_reason', sql`length(trim(${t.reason})) > 0`),
  ],
);

/**
 * The commercial audit trail: every plan assignment, plan change and override, with the value
 * before and after, who, when, why and until when. Append-only (the runtime role has no UPDATE or
 * DELETE on it; apps/api/sql/runtime-role.sql). Never deleted.
 */
export const commercialEvents = pgTable(
  'commercial_events',
  {
    seq: seq(),
    id: text('id').primaryKey(),
    event: text('event').notNull(),
    organizationId: text('organization_id').references(() => organizations.id),
    planKey: text('plan_key'),
    capability: text('capability'),
    /** The entity acted on when it is not an organization or plan ("user:…", "invoice:…"). */
    subject: text('subject'),
    oldValueJson: text('old_value_json'),
    newValueJson: text('new_value_json'),
    reason: text('reason').notNull(),
    expiresAt: isoTimestamp('expires_at'),
    actorUserId: text('actor_user_id')
      .notNull()
      .references(() => users.id),
    requestId: text('request_id'),
    createdAt: isoTimestamp('created_at').notNull(),
  },
  (t) => [
    check('commercial_events_event', inList(t.event, COMMERCIAL_EVENTS)),
    index('commercial_events_organization').on(t.organizationId, t.seq),
  ],
);

/**
 * What each reading of an invoice used (Control Centre cost accounting): one row per extraction,
 * so a retried job can never count the same reading twice; a new reading (a reprocess) is a real,
 * new cost and gets its own row. Usage only: never values, text or documents. Cost is calculated
 * from these counts and the pricing configured in Veyrafy Operations (`settings`), never stored
 * here, so a corrected rate applies everywhere. A ledger of what was spent: it has no foreign keys,
 * so it outlives the invoice (a demo reset, for example, does not erase real provider spend).
 */
export const processingUsage = pgTable(
  'processing_usage',
  {
    seq: seq(),
    id: text('id').primaryKey(),
    extractionId: text('extraction_id').notNull().unique(),
    invoiceId: text('invoice_id').notNull(),
    /** The readers that ran, joined ("ai_vision", "ai_vision+local_ocr", "local_ocr", …). */
    method: text('method').notNull(),
    pages: integer('pages').notNull(),
    aiModel: text('ai_model'),
    aiCalls: integer('ai_calls').notNull(),
    aiInputTokens: bigint('ai_input_tokens', { mode: 'number' }).notNull(),
    aiOutputTokens: bigint('ai_output_tokens', { mode: 'number' }).notNull(),
    durationMs: integer('duration_ms'),
    documentBytes: bigint('document_bytes', { mode: 'number' }).notNull(),
    createdAt: isoTimestamp('created_at').notNull(),
  },
  (t) => [
    index('processing_usage_created').on(t.createdAt),
    index('processing_usage_invoice').on(t.invoiceId),
  ],
);
