import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { ExtractionResultSchema } from '@veyra/shared';
import {
  ExtractorError,
  FixtureExtractor,
  PACKAGE_NAME,
  SCENARIOS,
  renderScenario,
  scenarioById,
  scenarioExtraction,
  scenarioMime,
  sha256Hex,
} from './index';

const FIXTURES = fileURLToPath(new URL('../../../fixtures/invoices/', import.meta.url));
const allowed = () => new FixtureExtractor({ allow: true, nodeEnv: 'test' });
const input = (id: string) => {
  const s = scenarioById(id);
  if (!s) throw new Error(id);
  const bytes = renderScenario(s);
  return { documentId: 'doc', filePath: s.file, mime: scenarioMime(s), sha256: sha256Hex(bytes) };
};

describe('@veyra/extractor', () => {
  it('exposes its package name', () => {
    expect(PACKAGE_NAME).toBe('@veyra/extractor');
  });
});

describe('FixtureExtractor is demo/test only', () => {
  it('refuses production, whatever the flag says', () => {
    expect(() => new FixtureExtractor({ allow: true, nodeEnv: 'production' })).toThrow(
      ExtractorError,
    );
  });

  it('refuses unless explicitly allowed', () => {
    expect(() => new FixtureExtractor({ allow: false, nodeEnv: 'development' })).toThrow(
      /VEYRA_ALLOW_FIXTURE_EXTRACTOR/,
    );
  });

  it('never reads a document it does not know: no guessing', async () => {
    await expect(
      allowed().extract({ documentId: 'x', filePath: 'x', mime: 'application/pdf', sha256: '0' }),
    ).rejects.toMatchObject({ code: 'UNKNOWN_DOCUMENT' });
  });
});

describe('fixture documents', () => {
  it('committed files are exactly the generated bytes (hashes are stable)', () => {
    for (const s of SCENARIOS) {
      const onDisk = readFileSync(`${FIXTURES}${s.file}`);
      expect(sha256Hex(onDisk), s.file).toBe(sha256Hex(renderScenario(s)));
    }
  });

  it('every scenario has a distinct document', () => {
    const hashes = SCENARIOS.map((s) => sha256Hex(renderScenario(s)));
    expect(new Set(hashes).size).toBe(SCENARIOS.length);
  });

  it('PDFs are PDFs and photos are PNGs', () => {
    for (const s of SCENARIOS) {
      const head = Buffer.from(renderScenario(s).subarray(0, 8));
      if (s.kind === 'pdf') expect(head.toString('latin1', 0, 5)).toBe('%PDF-');
      else expect(head.toString('latin1', 1, 4)).toBe('PNG');
    }
  });
});

describe('extraction output', () => {
  it('every scenario extracts to a valid ExtractionResult', () => {
    for (const s of SCENARIOS) {
      expect(ExtractionResultSchema.safeParse(scenarioExtraction(s)).success, s.id).toBe(true);
    }
  });

  it('reports facts, including weak reads, and decides nothing', async () => {
    const s17 = await allowed().extract(input('S17'));
    expect(s17.header.vendorGstin.confidenceBp).toBe(3500);
    const s14 = await allowed().extract(input('S14'));
    expect(s14.header.totalPaise).toMatchObject({ value: 1_606_800, confidenceBp: 4100 });
    const s06 = await allowed().extract(input('S06'));
    expect(s06.header.poNumber.value).toBe('PO-2026-0199');
    expect(s06.header.roundOffPaise.value).toBe(50);
  });

  it('absent fields are null with no evidence', async () => {
    const s03 = await allowed().extract(input('S03'));
    expect(s03.header.poNumber).toMatchObject({ value: null, evidence: null });
    expect(s03.header.igstPaise.value).toBeNull();
  });

  it('checks the mime type too', async () => {
    await expect(allowed().extract({ ...input('S01'), mime: 'image/png' })).rejects.toMatchObject({
      code: 'UNSUPPORTED_MIME',
    });
  });
});
